### ISSUE TITLE
`core.kepler` should return a single value if we're checking the gradients

### ISSUE THREAD

**Issue by soichiro-hattori** [exoplanet-dev/jaxoplanet#158]
The checks for PR #156 are failing due to some of the `test_grad` tests failing.
It's a bit odd because if I run the tests locally they all pass and it only seems to be an issue with the python 3.11 tests. 

I'm not entirely sure about the root cause of the tests failing but I think one potential issue is related to the fact that the `kepler` function actually returns 2 values.
Since JAX gradients are only defined for scalar-output functions, the following causes an error:
```python
jax.grad(kepler)(m, e)  # for some chosen values for the mean anomaly and eccentricity.
```
```
TypeError: Gradient only defined for scalar-output functions. Output was (Array(0.96160406, dtype=float32), Array(0.27444044, dtype=float32))
```

I'm not sure why `check_grads` is actually passing for certain cases given that `jax.grad(kepler)` shouldn't ever work?

@dfm: Should we return a single value from `kepler`?

**Comment by dfm** [comment]
Good question! The errors are actually stochastic (re-running normally fixes them) and only occur on macOS (I don't think it has anything to do with the Python version). The error message is about value mismatches, not a `TypeError`, so it's source isn't anything to do with the number of outputs. While `grad` is only defined for scalar outputs, [`check_grads`](https://github.com/google/jax/blob/2dd5e9e180febe65b9d0fee2f22e0f7804ca1be4/jax/_src/public_test_util.py#L267-L286) is well defined for any number of outputs because it tests the [JVP and VJP](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#how-it-s-made-two-foundational-autodiff-functions) directly.

`check_grads` does use random directions to check the gradients, but it looks like the random seed is fixed ([here](https://github.com/google/jax/blob/2dd5e9e180febe65b9d0fee2f22e0f7804ca1be4/jax/_src/public_test_util.py#L232) and [here](https://github.com/google/jax/blob/2dd5e9e180febe65b9d0fee2f22e0f7804ca1be4/jax/_src/public_test_util.py#L251)) so it's not clear why we would get stochastic failures.

In the short term our best bet might be to label that test with [xfail](https://docs.pytest.org/en/latest/how-to/skipping.html#xfail-mark-test-functions-as-expected-to-fail) on macOS, and continue testing it on linux.

**Comment by soichiro-hattori** [comment]
Ah I see! I did see in the output that the error was caused by the 'ValueError' instead of a 'TypeError' so that was another point I was confused about.

I reran the test earlier and it failed again (I saw that it passed now) so I thought it may have been something non-stochastic. 

Thanks! I'll close this for now.
