### ISSUE TITLE
Implement support for oblate stars in starry extension

### ISSUE THREAD

**Issue by dfm** [exoplanet-dev/jaxoplanet#20]
Of particular interest to @shashankdholakia, who may be able to sketch out a more fine grained plan for what steps are required. The key point here is that we're trying to avoid implementing custom C++ extensions, instead trying to stick to JAX directly. How painful would that be?

**Comment by shashankdholakia** [comment]
The main differences between the oblate transit model and the default starry model are a modified solution vector sT and a quartic solver rather than a quadratic solver to get the bounds of integration. So while I don't know the full details of the c++ implementation, I think it should be fairly easy to write in pure jax!

**Comment by dfm** [comment]
Thanks @shashankdholakia! Happy to chat at some point if you're feeling the urge to hack on this :D
