### ISSUE TITLE
Implement exposure time integration

### ISSUE THREAD

**Issue by dfm** [exoplanet-dev/jaxoplanet#6]
@soichiro-hattori

**Comment by dfm** [comment]
ref: https://github.com/exoplanet-dev/exoplanet/blob/main/src/exoplanet/light_curves/limb_dark.py

**Comment by soichiro-hattori** [comment]
I've implemented exposure time integration by rewriting some components in the ``light_curve`` method of the ``LimbDarkLightCurve`` class. The changes can be seen in the ``exposure_time_integration`` [branch of my fork](https://github.com/soichiro-hattori/jaxoplanet/tree/exposure_time_integration). 

I haven't run any tests for correctness so that's still necessary. I'll try to create an equivalent system with the ``exoplanet`` package and check for consistency.

A few questions:
1. The ``light_curve`` method currently returns a 2D array of the fluxes of shape ``(1, len(t))`` where ``t`` is an array of the times the flux is evaluated. Should we maintain this shape or should we just return a 1D array of shape ``(len(t))``?
2. I've renamed the ``order`` keyword argument in ``exoplanet`` used to specify the integration scheme for exposure time integration to ``texp_order`` in this code. This change was made since in ``jaxoplanet`` the ``order`` keyword argument was used to specify the polynomial order that gets passed to the ``scipy.special.roots_legendre`` function used in the ``limb_dark.py`` file within the ``core`` directory. This seems like a sensible choice but perhaps there's a better choice? 
3. This current version does not handle multiple values for ``r`` (the transiting bodies' radius) the way ``exoplanet`` does. My quick impression was that the ``orbit`` class in ``jaxoplanet`` is slightly differently from ``exoplanet`` in that it requires a value of ``r`` (unlike in ``exoplanet``). I wasn't quite sure of the best way to proceed so wanted to ask here what a good approach might be?

**Comment by soichiro-hattori** [comment]
I've made a quick comparison between the light curves, both with and without exposure time integration, that are produced by ``exoplanet (SimpleTransitOrbit)`` and ``jaxoplanet (TransitOrbit)`` using the same orbital/transit parameters (shown in the code snippets).

While I haven't done an extensive check of consistency through a range of different transit parameters, for the ones I've used here I saw that``np.allclose()`` evaluated to ``True`` for both the light curves (with and without exposure time integration) and that the differences are on the order of ~1e-17. 

Unrelated to this issue, but it wasn't possible to install both ``exoplanet`` and ``jaxoplanet`` to the same conda environment since there was a ``numpy`` version issue!

Here is the code used to generate the light curves using ``jaxoplanet`` and the figure that it produces.
```
import jaxoplanet
from jaxoplanet.light_curves import LimbDarkLightCurve
from jaxoplanet.orbits import TransitOrbit
import jax 
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt

jax.config.update(
    "jax_enable_x64", True
)  # For 64-bit precision since JAX defaults to 32-bit

# Define the parameters to pass to the TransitOrbit object
PERIOD = 10.0
DURATION = 0.1
T0 = 0.0
B = 0.0
R_STAR = 1.0
r = 0.1
orbit = TransitOrbit.init(period=PERIOD,
                     duration=DURATION,
                     time_transit=T0,
                     impact_param=B,
                     radius=r)

t = np.linspace(-0.1, 0.1, 500)
texp = 0.02

ld_lc = LimbDarkLightCurve.init()
lc = ld_lc.light_curve(orbit=orbit, t=t)[0]
texp_array = jnp.repeat(texp, len(t))
texp_lc = ld_lc.light_curve(orbit=orbit, t=t, texp=texp_array, texp_order=0)[0]  # "Resampling" procedure from Kipping 2010
# texp1_lc = ld_lc.light_curve(orbit=orbit, t=t, texp=texp_array, texp_order=1)[0]  # Trapezoidal rule
# texp2_lc = ld_lc.light_curve(orbit=orbit, t=t, texp=texp_array, texp_order=2)[0]  # Simpson's rule

fig, ax = plt.subplots(dpi=200, figsize=(7, 4))
ax.plot(t, lc, label=fr"$t_{{exp}} = 0.0$")
ax.plot(t, texp_lc, ls='--', label=fr"$t_{{exp}} = {texp}$ d")
# ax.plot(t, texp1_lc, ls='-.', label=fr"$t_{{exp}} = {texp}$, order=1")
# ax.plot(t, texp2_lc, ls=':', label=fr"$t_{{exp}} = {texp}$, order=2")

ax.legend()
ax.set_xlabel("Time [days]")
ax.set_ylabel("Relative Flux")
ax.annotate("jaxoplanet", xy=(0.5, 0.9), xycoords='axes fraction', ha='center')

# Save the light curves
# np.savetxt("jaxoplanet_no_texp_lc_flux.txt", lc)
# np.savetxt("jaxoplanet_texp_lc_flux.txt", texp_lc)
```
![image](https://github.com/exoplanet-dev/jaxoplanet/assets/4204544/df729a77-f2ea-414b-a9be-38eeafb8d78a)

The equivalent code for `exoplanet`
```
import numpy as np
import matplotlib.pyplot as plt
import exoplanet as xo
import aesara_theano_fallback.tensor as tt

# Define the parameters to pass to the TransitOrbit object
PERIOD = 10.0
DURATION = 0.1
T0 = 0.0
B = 0.0
R_STAR = 1.0
U = [0.0, 0.0]
r = 0.1

orbit = xo.orbits.SimpleTransitOrbit(period=PERIOD,
                                     duration=DURATION,
                                     t0=T0,
                                     b=B,
                                     r_star=R_STAR,
                                     ror=0.1)

t = np.linspace(-0.1, 0.1, 500)
texp = 0.02

ld_lc = xo.LimbDarkLightCurve(u1=U[0], u2=U[1])
lc = ld_lc.get_light_curve(orbit=orbit,
                           r=r,
                           t=t
).eval()
texp_lc = ld_lc.get_light_curve(orbit=orbit,
                                 r=r,
                                 t=t,
                                 texp=texp
).eval()

fig, ax = plt.subplots(dpi=200, figsize=(7, 4))
ax.plot(t, lc, c='C2', label=fr"$t_{{exp}} = 0.0$")
ax.plot(t, texp_lc, c='C3', ls='--', label=fr"$t_{{exp}} = {texp}$ d")
ax.legend()
ax.set_xlabel("Time [days]")
ax.set_ylabel("Relative Flux")
ax.annotate("exoplanet", xy=(0.5, 0.9), xycoords='axes fraction', ha='center')

# Save the light curves
# np.savetxt('exoplanet_no_texp_lc_flux.txt', lc)
# np.savetxt('exoplanet_texp_lc_flux.txt', texp_lc)
```
![image](https://github.com/exoplanet-dev/jaxoplanet/assets/4204544/097693b8-30f6-443e-837f-10553684b833)

And here is the code to make some comparison plots
```
exoplanet_lc_flux = np.loadtxt('exoplanet_no_texp_lc_flux.txt')
exoplanet_texp_lc_flux = np.loadtxt('exoplanet_texp_lc_flux.txt')
jaxoplanet_lc_flux = np.loadtxt('jaxoplanet_no_texp_lc_flux.txt')
jaxoplanet_texp_lc_flux = np.loadtxt('jaxoplanet_texp_lc_flux.txt')

print(f"Are the lcs with no texp the same (np.allclose): {np.allclose(exoplanet_lc_flux, jaxoplanet_lc_flux)}")
print(f"Are the lcs with texp=0.02 the same (np.allclose): {np.allclose(exoplanet_texp_lc_flux, jaxoplanet_texp_lc_flux)}")

fig, ax = plt.subplots(dpi=200, figsize=(7, 4))
ax.plot(t, jaxoplanet_lc_flux, label='jaxoplanet texp=0.0')
ax.plot(t, jaxoplanet_texp_lc_flux, label='jaxoplanet texp=0.02')
ax.plot(t, exoplanet_lc_flux, ls=':', label='exoplanet texp=0.0')
ax.plot(t, exoplanet_texp_lc_flux, ls=':', label='exoplanet texp=0.02')
ax.set_xlabel('Time [days]')
ax.set_ylabel('Relative Flux')
ax.legend()

fig, ax = plt.subplots(dpi=200, figsize=(7,4))
ax.plot(t, exoplanet_lc_flux-jaxoplanet_lc_flux, 'k.', mec='none', alpha=0.5, label='No texp')
ax.plot(t, exoplanet_texp_lc_flux-jaxoplanet_texp_lc_flux, 'r.', mec='none', alpha=0.5, label='texp=0.02')
ax.set_xlabel('Time [days]')
ax.set_ylabel('Difference [exoplanet - jaxoplanet]')
ax.legend();
```
```
Are the lcs with no texp the same (np.allclose): True
Are the lcs with texp=0.02 the same (np.allclose): True
```
![image](https://github.com/exoplanet-dev/jaxoplanet/assets/4204544/298b7aff-b0b6-46fc-ab06-4188757afa11)

![image](https://github.com/exoplanet-dev/jaxoplanet/assets/4204544/75cc8a63-d321-4247-a3d8-6ae917f9b82a)

**Comment by dfm** [comment]
This looks awesome - thank you!! Can you open a PR with the changes you've made so far and we can discuss there? As for your questions:

> 1. The ``light_curve`` method currently returns a 2D array of the fluxes of shape ``(1, len(t))`` where ``t`` is an array of the times the flux is evaluated. Should we maintain this shape or should we just return a 1D array of shape ``(len(t))``?

In `exoplanet`, the shape returned by `light_curve` is `(num_planets, len(t))`, I believe. I think we probably want something like that here too (I expect that's where the `1` comes from, but it's been a while :D)

> 2. I've renamed the ``order`` keyword argument in ``exoplanet`` used to specify the integration scheme for exposure time integration to ``texp_order`` in this code. This change was made since in ``jaxoplanet`` the ``order`` keyword argument was used to specify the polynomial order that gets passed to the ``scipy.special.roots_legendre`` function used in the ``limb_dark.py`` file within the ``core`` directory. This seems like a sensible choice but perhaps there's a better choice? 

This makes sense to me, and perhaps we should rename `order` to something else, maybe like `limbdark_order`, so that people don't get confused?

> 3. This current version does not handle multiple values for ``r`` (the transiting bodies' radius) the way ``exoplanet`` does. My quick impression was that the ``orbit`` class in ``jaxoplanet`` is slightly differently from ``exoplanet`` in that it requires a value of ``r`` (unlike in ``exoplanet``). I wasn't quite sure of the best way to proceed so wanted to ask here what a good approach might be?

In general the way we're handling multiple planets might take some work to get sorted properly. Let's not think about it too much right now, and we can touch base in person.
