### ISSUE TITLE
Error creating LimbDarkLightCurve due to jpu units?

### ISSUE THREAD

**Issue by shashankdholakia** [exoplanet-dev/jaxoplanet#84]
I'm getting an error when trying to compute a limb darkened light curve with the latest dev version of jaxoplanet. I think this is related to the introduction of jax units. Here is an MWE to reproduce the error:

```python
from jaxoplanet.light_curves import LimbDarkLightCurve
from jaxoplanet import light_curves, orbits
import jax.numpy as jnp
import matplotlib.pyplot as plt

#Fiducial planet parameters:
params = {'period':300.456,
          'radius':0.1,
          'u':jnp.array([0.3,0.2]),
          'bo':0.8,
}
# The light curve calculation requires an orbit
orbit = orbits.keplerian.Body(period=params['period'], radius=params['radius'], impact_param=params['bo'])

# Compute a limb-darkened light curve using jaxoplanet
t = jnp.linspace(-0.3, 0.3, 1000)

lc = LimbDarkLightCurve(params['u']).light_curve(orbit, t=t)

plt.plot(t, lc[0], color="C0", lw=2)
plt.ylabel("relative flux")
plt.xlabel("time [days]")
_ = plt.xlim(t.min(), t.max())
```

which returns: `TypeError: Unexpected input type for array: `

**Comment by soichiro-hattori** [comment]
Hi @shashankdholakia! Thanks for bringing this issue up. There was a small bug where we weren't calling the correct functions. We should have been calling `jpu.numpy` functions instead of `jnp.numpy` functions when using the arrays with units (e.g., `t`). The changes made in PR #86 should fix this issue but let us know if it still doesn't!

One small change is that the `light_curve` function now returns a 1D array with size `len(t)` so you won't need to index the first element of `lc` when plotting the flux (`lc[0] -> lc`)!

**Comment by shashankdholakia** [comment]
Thanks, this fixed it!
